name: Generate Codecov Report

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  codecov_report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
          
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run jacoco
      run: ./gradlew jacocoTestReport

    - name: Generate report
      uses: actions/upload-artifact@v2
      with:
        name: report 
        path: ./agent-ndk/build/reports/coverage/androidTest/debug/connected


    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: report
        path: ./agent-ndk/build/reports/coverage/androidTest/debug/connected

    - name: Upload Test Report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: "./agent-ndk/build/reports/coverage/androidTest/debug/connected/report.xml"